# Generated by Django 4.2.1 on 2023-06-12 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.CharField(db_column='DeviceID', max_length=255, primary_key=True, serialize=False)),
                ('device', models.CharField(blank=True, db_column='Device', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batt', models.FloatField(blank=True, db_column='Batt', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('devEui', models.ForeignKey(blank=True, db_column='DeviceID', null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.devices')),
            ],
        ),
        migrations.CreateModel(
            name='NPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(blank=True, db_column='Nitrogen ', null=True)),
                ('phosphorus', models.FloatField(blank=True, db_column='Phosphorus ', null=True)),
                ('potassium', models.FloatField(blank=True, db_column='Potassium ', null=True)),
                ('batt', models.FloatField(blank=True, db_column='Batt', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('devEui', models.ForeignKey(blank=True, db_column='DeviceID', null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.devices')),
            ],
        ),
        migrations.CreateModel(
            name='MoistureTempEcSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(blank=True, db_column='Temp', null=True)),
                ('ec', models.FloatField(blank=True, db_column='Ec', null=True)),
                ('sal', models.FloatField(blank=True, db_column='Sal', null=True)),
                ('batt', models.FloatField(blank=True, db_column='Batt', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('devEui', models.ForeignKey(blank=True, db_column='DeviceID', null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.devices')),
            ],
        ),
    ]
