# Generated by Django 4.2 on 2023-06-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batvanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat', models.FloatField(null=True)),
                ('dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.IntegerField()),
                ('Temp', models.FloatField(null=True)),
                ('Hum', models.FloatField(null=True)),
                ('Ec', models.FloatField(null=True)),
                ('Sal', models.FloatField(null=True)),
                ('Bat', models.FloatField(null=True)),
                ('time', models.TimeField(auto_now=True)),
                ('dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapSol2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.IntegerField()),
                ('Temp', models.FloatField(null=True)),
                ('Hum', models.FloatField(null=True)),
                ('Ec', models.FloatField(null=True)),
                ('Sal', models.FloatField(null=True)),
                ('Bat', models.FloatField(null=True)),
                ('dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Device', models.IntegerField()),
                ('Temp', models.FloatField(null=True)),
                ('Hum', models.FloatField(null=True)),
                ('Ray', models.FloatField(null=True)),
                ('Wind_Speed', models.FloatField(null=True)),
                ('Rain', models.FloatField(null=True)),
                ('Bat', models.FloatField(null=True)),
                ('alt', models.FloatField(null=True)),
                ('pr', models.FloatField(null=True)),
                ('d', models.FloatField(null=True)),
                ('Time_Stamp', models.DateTimeField(auto_now_add=True)),
                ('i', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mqtt_Channel',
            fields=[
                ('mqtt_channel_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='vann',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onoff', models.BooleanField()),
                ('dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
