# Generated by Django 4.2 on 2023-06-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0002_alter_data_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Bat',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Hum',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Rain',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Ray',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Temp',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Time_Stamp',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Wind_Speed',
        ),
        migrations.RemoveField(
            model_name='data',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='data',
            name='d',
        ),
        migrations.RemoveField(
            model_name='data',
            name='i',
        ),
        migrations.RemoveField(
            model_name='data',
            name='pr',
        ),
    ]
