# Generated by Django 4.2 on 2023-06-19 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0003_remove_data_bat_remove_data_hum_remove_data_rain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Bat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Hum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Rain',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Ray',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Time_Stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='Wind_Speed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='alt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='d',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='i',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='pr',
            field=models.FloatField(null=True),
        ),
    ]
