# Generated by Django 4.2 on 2023-06-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0004_data_bat_data_hum_data_rain_data_ray_data_temp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
