# Generated by Django 4.2 on 2023-06-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0005_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Device', models.IntegerField()),
                ('Temp', models.FloatField(null=True)),
                ('Hum', models.FloatField(null=True)),
                ('Ray', models.FloatField(null=True)),
                ('Wind_Speed', models.FloatField(null=True)),
                ('Rain', models.FloatField(null=True)),
                ('Time_Stamp', models.DateTimeField(auto_now_add=True)),
                ('Bat', models.FloatField(null=True)),
                ('alt', models.FloatField(null=True)),
                ('pr', models.FloatField(null=True)),
                ('d', models.FloatField(null=True)),
                ('i', models.IntegerField(null=True)),
            ],
        ),
    ]
