# Generated by Django 4.2 on 2023-06-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0006_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapSol',
        ),
    ]
