# Generated by Django 4.2 on 2023-06-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0007_delete_capsol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.IntegerField()),
                ('Temp', models.FloatField(null=True)),
                ('Hum', models.FloatField(null=True)),
                ('Ec', models.FloatField(null=True)),
                ('Sal', models.FloatField(null=True)),
                ('Bat', models.FloatField(null=True)),
                ('dt', models.DateTimeField(auto_now=True, null=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
