# Generated by Django 4.2 on 2023-06-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0008_capsol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vann',
        ),
    ]
