# Generated by Django 4.2 on 2023-06-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0009_delete_vann'),
    ]

    operations = [
        migrations.CreateModel(
            name='vann',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True, null=True)),
                ('onoff', models.BooleanField()),
            ],
        ),
    ]
