# Generated by Django 4.2 on 2023-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0010_vann'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveFlow',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Flow', models.FloatField()),
            ],
        ),
    ]
