# Generated by Django 4.2.1 on 2023-07-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0011_valveflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capnpk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.IntegerField()),
                ('Azote', models.FloatField(null=True)),
                ('Phosphore', models.FloatField(null=True)),
                ('Potassium', models.FloatField(null=True)),
                ('Bat', models.FloatField(null=True)),
                ('dt', models.DateTimeField(auto_now=True, null=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
