# Generated by Django 4.2.1 on 2023-07-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAGRI', '0012_capnpk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capnpk',
            old_name='Azote',
            new_name='Azoute',
        ),
    ]
